{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kr328.clash",
    "module": "core",
    "version": "2.4.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "fossReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.4.14.aar",
          "url": "core-2.4.14.aar",
          "size": 26871047,
          "sha512": "c39f8092c1ea009e1867750f141773a6f7420de2ca756e5af2b1a59895d167077bf36dbaef8b122c9a079c496079fd7ec228c391599a63e9c4f03e8aad38abb1",
          "sha256": "9cacd2a43ef0f01f4b9382a806f4bd3efd9aa2e431ef2dbc6631e184be9d4f3b",
          "sha1": "4e343f6d3b9ba76deda77963015a595b25dae1c3",
          "md5": "27a0fff24a00b3c6f83fce30841a2e1e"
        }
      ]
    },
    {
      "name": "fossReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.github.kr328.clash",
          "module": "common",
          "version": {
            "requires": "2.4.14"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.4.14.aar",
          "url": "core-2.4.14.aar",
          "size": 26871047,
          "sha512": "c39f8092c1ea009e1867750f141773a6f7420de2ca756e5af2b1a59895d167077bf36dbaef8b122c9a079c496079fd7ec228c391599a63e9c4f03e8aad38abb1",
          "sha256": "9cacd2a43ef0f01f4b9382a806f4bd3efd9aa2e431ef2dbc6631e184be9d4f3b",
          "sha1": "4e343f6d3b9ba76deda77963015a595b25dae1c3",
          "md5": "27a0fff24a00b3c6f83fce30841a2e1e"
        }
      ]
    }
  ]
}
