{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kr328.clash",
    "module": "common",
    "version": "2.4.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "fossReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "common-2.4.14.aar",
          "url": "common-2.4.14.aar",
          "size": 61574,
          "sha512": "714182ec77ab62463e22a480dc100860d49ce29581e6bb09f87452d96b072713604a69c2e2bdafd5565faaab73c2067c6305d9ddc65924b11f96115b1c410cd5",
          "sha256": "6d0cdd2773b40e3d7580cd7ff7c8e93a4fdfedd69c83dabef807382688d72d42",
          "sha1": "d3a0712b56344f1ac59af7f7ee3a854dd321ea51",
          "md5": "7e95c8b1b41154044753110f9f585df7"
        }
      ]
    },
    {
      "name": "fossReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-2.4.14.aar",
          "url": "common-2.4.14.aar",
          "size": 61574,
          "sha512": "714182ec77ab62463e22a480dc100860d49ce29581e6bb09f87452d96b072713604a69c2e2bdafd5565faaab73c2067c6305d9ddc65924b11f96115b1c410cd5",
          "sha256": "6d0cdd2773b40e3d7580cd7ff7c8e93a4fdfedd69c83dabef807382688d72d42",
          "sha1": "d3a0712b56344f1ac59af7f7ee3a854dd321ea51",
          "md5": "7e95c8b1b41154044753110f9f585df7"
        }
      ]
    }
  ]
}
