{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kr328.clash",
    "module": "service",
    "version": "2.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "fossReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "service-2.4.6.aar",
          "url": "service-2.4.6.aar",
          "size": 453056,
          "sha512": "e66620fa01c5cfdd21812a00dbf42756cde8539dc1f9032b3137d45b81774f319dc240d5522396ed052e08856fb02f2f9f9e10c88bfed4dee17461daa4de52b9",
          "sha256": "267326e56627022e775b61bca345729519ac369507914210e43f413f8e7ae6bd",
          "sha1": "d400eb4fce1a08d23e6d964e89f4e6aa1a3c9053",
          "md5": "f5fc11b1d5caa9cbaf27c9ede648c509"
        }
      ]
    },
    {
      "name": "fossReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.github.kr328.clash",
          "module": "core",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "com.github.kr328.clash",
          "module": "common",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.github.kr328.kaidl",
          "module": "kaidl-runtime",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "dev.rikka.rikkax.preference",
          "module": "multiprocess",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "service-2.4.6.aar",
          "url": "service-2.4.6.aar",
          "size": 453056,
          "sha512": "e66620fa01c5cfdd21812a00dbf42756cde8539dc1f9032b3137d45b81774f319dc240d5522396ed052e08856fb02f2f9f9e10c88bfed4dee17461daa4de52b9",
          "sha256": "267326e56627022e775b61bca345729519ac369507914210e43f413f8e7ae6bd",
          "sha1": "d400eb4fce1a08d23e6d964e89f4e6aa1a3c9053",
          "md5": "f5fc11b1d5caa9cbaf27c9ede648c509"
        }
      ]
    }
  ]
}
