{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kr328.clash",
    "module": "core",
    "version": "2.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "fossReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.4.6.aar",
          "url": "core-2.4.6.aar",
          "size": 26871047,
          "sha512": "2f6bd704b71c8feb61f051f396296801ebdec63ac6270d944efe84069c0347db998b641a33f778bdaeb23c9f901a3e482e6e63e3a4c527e7f521ccb1b03217ec",
          "sha256": "7a9aa7f6450f8ba530bb955c95fc8b5ec697ecc69bece3626120671fc3faa5b9",
          "sha1": "35c2720afec00db2800002dc0cf1a9a891699f22",
          "md5": "e33ea1516427cc555d8a400a24d64bd5"
        }
      ]
    },
    {
      "name": "fossReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.github.kr328.clash",
          "module": "common",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.4.6.aar",
          "url": "core-2.4.6.aar",
          "size": 26871047,
          "sha512": "2f6bd704b71c8feb61f051f396296801ebdec63ac6270d944efe84069c0347db998b641a33f778bdaeb23c9f901a3e482e6e63e3a4c527e7f521ccb1b03217ec",
          "sha256": "7a9aa7f6450f8ba530bb955c95fc8b5ec697ecc69bece3626120671fc3faa5b9",
          "sha1": "35c2720afec00db2800002dc0cf1a9a891699f22",
          "md5": "e33ea1516427cc555d8a400a24d64bd5"
        }
      ]
    }
  ]
}
